development:
    adapter: postgresql
    host: localhost
    database: nrcanhockey_dev

test:
    adapter: postgresql
    host: localhost
    database: ballhockey_test

production:
    adapter: postgresql
    host: localhost
    database: ballhockey_prod

