development:
    adapter: mysql2
    host: smyth100.local
    database: nrcanhockey_dev
    username: root
    password: upandatom

test:
    adapter: mysql2
    host: smyth100.local
    database: nrcanhockey_test
    username: root
    password: upandatom

production:
    adapter: mysql2
    host: smyth100.local
    database: nrcanhockey_prod
    username: root
    password: upandatom

