development:
    adapter: postgresql
    host: localhost
    database: nrcanhockey_dev

test:
    adapter: postgresql
    host: localhost
    database: nrcanhockey_test

production:
    adapter: postgresql
    host: localhost
    database: nrcanhockey_prod

