development:
    adapter: mysql2
    host: localhost
    database: nrcanhockey_dev
    username: root
    password: 

test:
    adapter: mysql2
    host: localhost
    database: nrcanhockey_test
    username: root
    password: 

production:
    adapter: mysql2
    host: slocalhost
    database: nrcanhockey_prod
    username: root
    password: 

